### ISSUE TITLE
refactoring: wrap i funktion

### ISSUE THREAD

**Issue by JosefMikkelsen** [ballerupgis/qlr-datasource-rename#7]
Jeg vil gerne refactore koden lidt så vi bruger den klassiske `__main__` form. eksempel:

Før:

``` python
print("hello world")
```

Efter:

``` python
def foo():
    print("hello world")

if __name__ == "__main__":
    foo()
```

**Comment by baffioso** [comment]
@JosefAssad kan du beskrive med et par ord hvad denne ændring gør?

**Comment by JosefMikkelsen** [comment]
Yep!

Det der udtryk `if __name__ == "__main__":` checker om scriptet køres direkte; det gør vi nu, vi kalder `python3 qlr-datasource-rename.py`. Men det er også muligt at bruge koden på en anden måde, for eksempel hvis vi skriver noget andet kode `blabla.py` og skal bruge funktionen `foo()`. I så fald kan vi importere `qlr-datasource-rename` som modul i `blabla.py` og for eksempel kalde funktionen `qlr-datasource-rename.foo` i `blabla.py`. Så kører vi `python3 blabla.py` og så bruger den `foo()` uden at selve scriptet `qlr-datasource-rename.py` kører direkte.

Den form med andre ord tillader at vi bruger vores kode enten som direkte eksekverbar script eller som importerbar modul i anden sammenhæng.

Makes sense?

**Comment by baffioso** [comment]
Ja det gør det. God måde at bryde sin kode op (minder om det jeg er ved at lære i JS)
